### ISSUE TITLE
keyerror

### ISSUE THREAD

**Issue by PiotrLuczko** [abhishekdelta/tragit#1]
Github API successfully loaded!
Creating label : {'color': '0011FF', 'name': u'Unknown'}
Creating label : {'color': 'FF7777', 'name': u'major'}
Creating label : {'color': '0011FF', 'name': u'None'}
Traceback (most recent call last):
  File "tragit.py", line 195, in <module>
    tragit.transfer()
  File "tragit.py", line 127, in transfer
    self._process_ticket(row)
  File "tragit.py", line 181, in _process_ticket
    issue_id = self._github.create_issue(ticket[self._conf_map['title']], ticket
[self._conf_map['body']],
KeyError: 'description'

**Comment by abhishekdelta** [comment]
It is due to the 'description' column missing from your trac csv file. You have to modify the tragit.conf file to tell it which column in your traccsv file represents the body of the ticket. By default its 'description' column.
